// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreWeb.Repositories;

#nullable disable

namespace StoreWeb.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260407133759_ImageURLToProduct")]
    partial class ImageURLToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("StoreWeb.Repositories.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageURL = "images/1.jpg",
                            Price = 45999.90m,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            ProductId = 2,
                            ImageURL = "images/2.jpg",
                            Price = 899.50m,
                            ProductName = "Wireless Mouse"
                        },
                        new
                        {
                            ProductId = 3,
                            ImageURL = "images/3.jpg",
                            Price = 2499.00m,
                            ProductName = "Mechanical Keyboard"
                        },
                        new
                        {
                            ProductId = 4,
                            ImageURL = "images/4.jpg",
                            Price = 12999.00m,
                            ProductName = "27-inch Monitor"
                        },
                        new
                        {
                            ProductId = 5,
                            ImageURL = "images/5.jpg",
                            Price = 3199.90m,
                            ProductName = "Bluetooth Headphones"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
